// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4c992FUYvuQiZd1RamSXMuAFIfeRd79w',
    appId: '1:382406425954:web:51d7579c24b5c84987003b',
    messagingSenderId: '382406425954',
    projectId: 'my-grad-capital',
    authDomain: 'my-grad-capital.firebaseapp.com',
    storageBucket: 'my-grad-capital.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFjRa1MvFGt0H8oR9yWVsMh7p2Eqo1ckQ',
    appId: '1:382406425954:android:1c5dc41f7e0ace0287003b',
    messagingSenderId: '382406425954',
    projectId: 'my-grad-capital',
    storageBucket: 'my-grad-capital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgLP8dfJlGDcbpl_YUB4NsuWUFoz2qs6c',
    appId: '1:382406425954:ios:6b1bb1c8b409a10f87003b',
    messagingSenderId: '382406425954',
    projectId: 'my-grad-capital',
    storageBucket: 'my-grad-capital.appspot.com',
    iosClientId: '382406425954-h39slmns4269r98blt6o1c84j4aj0gsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgLP8dfJlGDcbpl_YUB4NsuWUFoz2qs6c',
    appId: '1:382406425954:ios:6b1bb1c8b409a10f87003b',
    messagingSenderId: '382406425954',
    projectId: 'my-grad-capital',
    storageBucket: 'my-grad-capital.appspot.com',
    iosClientId: '382406425954-h39slmns4269r98blt6o1c84j4aj0gsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp1',
  );
}
